-- ==========================================
-- 1. TEAMS & PLAYERS (The Foundation)
-- ==========================================

CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    short_name TEXT,
    logo_url TEXT,
    logo TEXT
);

CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES teams(id),
    name TEXT NOT NULL,
    role TEXT, -- 'Batsman', 'Bowler', 'All-Rounder', 'Wicketkeeper'
    batting_style TEXT,
    bowling_style TEXT,
    runs INTEGER DEFAULT 0,
    balls INTEGER DEFAULT 0,
    fours INTEGER DEFAULT 0,
    sixes INTEGER DEFAULT 0,
    is_out BOOLEAN DEFAULT FALSE,
    details TEXT,
    photo_url TEXT DEFAULT NULL
);

-- ==========================================
-- 2. TOURNAMENTS (New Feature)
-- ==========================================

CREATE TABLE IF NOT EXISTS tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_date DATE,
    end_date DATE,
    status TEXT DEFAULT 'upcoming', -- upcoming, active, completed
    logo_url TEXT
);

-- ==========================================
-- 3. MATCHES (Updated with New Settings)
-- ==========================================

CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Core Links
    tournament_id BIGINT REFERENCES tournaments(id),
    match_number INTEGER, -- e.g. Match 1, Match 2
    
    -- Teams Involved (ID references are better than Text names)
    team_a_id BIGINT REFERENCES teams(id),
    team_b_id BIGINT REFERENCES teams(id),
    
    -- Legacy Text Names (Keep for safety if old code uses them)
    team_name_batting TEXT DEFAULT 'Home Team',
    team_name_bowling TEXT DEFAULT 'Away Team',
    
    -- Match Configuration (NEW COLUMNS FOR SETTINGS MODAL)
    total_overs INTEGER DEFAULT 20,      -- e.g. 5, 10, 20, 50
    balls_per_over INTEGER DEFAULT 6,    -- e.g. 6 (Standard), 5 (The Hundred)
    match_type TEXT DEFAULT 'League Match', -- e.g. Group, Final, Semi-Final
    match_status TEXT DEFAULT 'scheduled',  -- scheduled, live, completed (Renamed from 'status' to avoid confusion)
    
    -- Live Match State
    current_inning INTEGER DEFAULT 1,
    team_score INTEGER DEFAULT 0,
    wickets INTEGER DEFAULT 0,
    overs INTEGER DEFAULT 0,      -- Completed overs
    balls INTEGER DEFAULT 0,      -- Valid balls in current over
    
    -- Toss & Decision (NEW)
    toss_winner_id BIGINT REFERENCES teams(id),
    toss_decision TEXT,           -- 'bat' or 'bowl'
    
    -- Current Active Players (Live State)
    batting_team_id BIGINT REFERENCES teams(id), -- Who is batting NOW?
    bowling_team_id BIGINT REFERENCES teams(id), -- Who is bowling NOW?
    current_striker_id BIGINT REFERENCES players(id),
    non_striker_id BIGINT REFERENCES players(id),
    current_bowler_id BIGINT REFERENCES players(id),
    
    -- Timing
    match_date DATE,
    start_time TIME,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 4. BALLS (The Source of Truth)
-- ==========================================

CREATE TABLE IF NOT EXISTS balls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE,
    inning_no INTEGER DEFAULT 1,
    over_no INTEGER,      -- e.g. 0, 1, 2...
    ball_no INTEGER,      -- e.g. 1, 2, 3... (Valid ball count)
    
    -- Player Links
    striker_id BIGINT REFERENCES players(id),
    non_striker_id BIGINT REFERENCES players(id),
    bowler_id BIGINT REFERENCES players(id),
    
    -- Scoring Details
    runs_off_bat INTEGER DEFAULT 0,
    extras INTEGER DEFAULT 0, 
    extra_type TEXT, -- 'wide', 'noball', 'bye', 'leg-bye'
    
    -- Boundaries & Wickets
    is_four BOOLEAN DEFAULT FALSE,
    is_six BOOLEAN DEFAULT FALSE,
    is_wicket BOOLEAN DEFAULT FALSE,
    wicket_type TEXT, -- Caught, Bowled, etc.
    player_out_id BIGINT REFERENCES players(id),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 5. MATCH SQUADS (Playing 11)
-- ==========================================

CREATE TABLE IF NOT EXISTS match_squads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE,
    player_id BIGINT REFERENCES players(id),
    is_playing_11 BOOLEAN DEFAULT FALSE
);

-- ==========================================
-- 6. COMMENTARY (For Future Use)
-- ==========================================

CREATE TABLE IF NOT EXISTS commentary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE,
    inning INTEGER DEFAULT 1,
    over_number NUMERIC(4,1), -- e.g. 1.4
    ball_id BIGINT REFERENCES balls(id),
    text TEXT,
    event_type TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 7. PERFORMANCE INDEXES (Speed Optimization)
-- ==========================================

-- 1. Accelerate Score Calculation (Used in fetch_full_match_state)
-- Speeds up: SELECT SUM(runs) FROM balls WHERE match_id = X
CREATE INDEX IF NOT EXISTS idx_balls_match_inning 
ON balls (match_id, inning_no);

-- 2. Accelerate Player Stats (Used for Batsman/Bowler Cards)
-- Speeds up: SELECT runs FROM balls WHERE striker_id = Y
CREATE INDEX IF NOT EXISTS idx_balls_striker 
ON balls (striker_id);

CREATE INDEX IF NOT EXISTS idx_balls_bowler 
ON balls (bowler_id);

-- 3. Accelerate Match Lookups
CREATE INDEX IF NOT EXISTS idx_matches_teams 
ON matches (team_a_id, team_b_id);

-- 4. Accelerate Wicket Lookups
CREATE INDEX IF NOT EXISTS idx_wickets_ball_id 
ON wickets (ball_id);